-- Add is_manual column to clusters table
ALTER TABLE public.clusters 
ADD COLUMN IF NOT EXISTS is_manual BOOLEAN NOT NULL DEFAULT false;

-- Add comment to explain the column
COMMENT ON COLUMN public.clusters.is_manual IS 'Indicates whether the cluster was manually created by the user (true) or auto-generated by AI (false)';